# Helm values for test.
# Overrides default values only for environment-specific settings.

namespace: devloop-demo-test

appEnv: Test

image: ghcr.io/creid-octopus/composite-development-loop:1.0.7-sha-f6a65a3
