apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Values.namespace }}
data:
  # property-like keys; each key maps to a simple value
  APP_ENV: {{ .Values.appEnv | quote }}
